global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'php-backend'
    static_configs:
      - targets: ['php-backend:8000']
        labels:
          __metrics_path__: /metrics.php
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
